// <auto-generated />
using System;
using AI.TestPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AI.TestPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20260821132524_AddAllowPrivateNetworkImport")]
    partial class AddAllowPrivateNetworkImport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.AIElementCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ElementDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("LastMatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchCount")
                        .HasColumnType("integer");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "PageUrl", "ElementDescription")
                        .IsUnique();

                    b.ToTable("AIElementCaches");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.ApiDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EndpointCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ApiDefinitions");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoLogin")
                        .HasColumnType("boolean");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginPassword")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LoginSuccessIndicator")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("LoginUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LoginUsername")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.Execution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AIDiagnosis")
                        .HasColumnType("text");

                    b.Property<string>("AISuggestedFix")
                        .HasColumnType("text");

                    b.Property<string>("BrowserVersion")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("DiagnosisConfidence")
                        .HasColumnType("real");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("TriggerType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TriggeredById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("TestCaseId");

                    b.HasIndex("TriggeredById");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("Executions");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.ExecutionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Log")
                        .HasColumnType("text");

                    b.Property<string>("ScreenshotUrl")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TestStepId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TestStepId");

                    b.HasIndex("ExecutionId", "StepOrder");

                    b.ToTable("ExecutionResults");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.MockDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BasePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Port")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("MockDefinitions");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AiBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("AiMaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AllowPrivateNetworkImport")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebhookToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("SystemConfigs");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AIGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("AIPrompt")
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("Browser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Timeout")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.TestStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AIElementDescription")
                        .HasColumnType("text");

                    b.Property<string>("AIInstruction")
                        .HasColumnType("text");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId", "StepOrder");

                    b.ToTable("TestSteps");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.AIElementCache", b =>
                {
                    b.HasOne("AI.TestPlatform.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("AI.TestPlatform.Domain.Entities.SelectorHistoryEntry", "SelectorHistory", b1 =>
                        {
                            b1.Property<Guid>("AIElementCacheId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<float>("Confidence")
                                .HasColumnType("real");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AIElementCacheId", "Id");

                            b1.ToTable("AIElementCaches");

                            b1.ToJson("SelectorHistory");

                            b1.WithOwner()
                                .HasForeignKey("AIElementCacheId");
                        });

                    b.Navigation("Project");

                    b.Navigation("SelectorHistory");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.ApiDefinition", b =>
                {
                    b.HasOne("AI.TestPlatform.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.Environment", b =>
                {
                    b.HasOne("AI.TestPlatform.Domain.Entities.Project", "Project")
                        .WithMany("Environments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.Execution", b =>
                {
                    b.HasOne("AI.TestPlatform.Domain.Entities.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AI.TestPlatform.Domain.Entities.TestCase", "TestCase")
                        .WithMany("Executions")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AI.TestPlatform.Domain.Entities.User", "TriggeredBy")
                        .WithMany()
                        .HasForeignKey("TriggeredById");

                    b.OwnsOne("AI.TestPlatform.Domain.Entities.EnvironmentSnapshot", "EnvironmentSnapshot", b1 =>
                        {
                            b1.Property<Guid>("ExecutionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BaseUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("ExecutionId");

                            b1.ToTable("Executions");

                            b1.ToJson("EnvironmentSnapshot");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionId");
                        });

                    b.Navigation("Environment");

                    b.Navigation("EnvironmentSnapshot");

                    b.Navigation("TestCase");

                    b.Navigation("TriggeredBy");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.ExecutionResult", b =>
                {
                    b.HasOne("AI.TestPlatform.Domain.Entities.Execution", "Execution")
                        .WithMany("Results")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.TestPlatform.Domain.Entities.TestStep", "TestStep")
                        .WithMany()
                        .HasForeignKey("TestStepId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("AI.TestPlatform.Domain.Entities.StepConfig", "StepSnapshot", b1 =>
                        {
                            b1.Property<Guid>("ExecutionResultId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .HasColumnType("text");

                            b1.Property<string>("Endpoint")
                                .HasColumnType("text");

                            b1.Property<string>("Method")
                                .HasColumnType("text");

                            b1.Property<string>("Url")
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .HasColumnType("text");

                            b1.HasKey("ExecutionResultId");

                            b1.ToTable("ExecutionResults");

                            b1.ToJson("StepSnapshot");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionResultId");

                            b1.OwnsMany("AI.TestPlatform.Domain.Entities.HeaderEntry", "Headers", b2 =>
                                {
                                    b2.Property<Guid>("StepConfigExecutionResultId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("StepConfigExecutionResultId", "Id");

                                    b2.ToTable("ExecutionResults");

                                    b2.WithOwner()
                                        .HasForeignKey("StepConfigExecutionResultId");
                                });

                            b1.OwnsOne("AI.TestPlatform.Domain.Entities.SelectorConfig", "Selector", b2 =>
                                {
                                    b2.Property<Guid>("StepConfigExecutionResultId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Description")
                                        .HasColumnType("text");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Value")
                                        .HasColumnType("text");

                                    b2.HasKey("StepConfigExecutionResultId");

                                    b2.ToTable("ExecutionResults");

                                    b2.WithOwner()
                                        .HasForeignKey("StepConfigExecutionResultId");
                                });

                            b1.Navigation("Headers");

                            b1.Navigation("Selector");
                        });

                    b.Navigation("Execution");

                    b.Navigation("StepSnapshot");

                    b.Navigation("TestStep");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.MockDefinition", b =>
                {
                    b.HasOne("AI.TestPlatform.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.Project", b =>
                {
                    b.HasOne("AI.TestPlatform.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.TestCase", b =>
                {
                    b.HasOne("AI.TestPlatform.Domain.Entities.TestCase", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AI.TestPlatform.Domain.Entities.Project", "Project")
                        .WithMany("TestCases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.TestStep", b =>
                {
                    b.HasOne("AI.TestPlatform.Domain.Entities.TestCase", "TestCase")
                        .WithMany("Steps")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AI.TestPlatform.Domain.Entities.StepConfig", "Config", b1 =>
                        {
                            b1.Property<Guid>("TestStepId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .HasColumnType("text");

                            b1.Property<string>("Endpoint")
                                .HasColumnType("text");

                            b1.Property<string>("Method")
                                .HasColumnType("text");

                            b1.Property<string>("Url")
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .HasColumnType("text");

                            b1.HasKey("TestStepId");

                            b1.ToTable("TestSteps");

                            b1.ToJson("Config");

                            b1.WithOwner()
                                .HasForeignKey("TestStepId");

                            b1.OwnsMany("AI.TestPlatform.Domain.Entities.HeaderEntry", "Headers", b2 =>
                                {
                                    b2.Property<Guid>("StepConfigTestStepId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("StepConfigTestStepId", "Id");

                                    b2.ToTable("TestSteps");

                                    b2.WithOwner()
                                        .HasForeignKey("StepConfigTestStepId");
                                });

                            b1.OwnsOne("AI.TestPlatform.Domain.Entities.SelectorConfig", "Selector", b2 =>
                                {
                                    b2.Property<Guid>("StepConfigTestStepId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Description")
                                        .HasColumnType("text");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Value")
                                        .HasColumnType("text");

                                    b2.HasKey("StepConfigTestStepId");

                                    b2.ToTable("TestSteps");

                                    b2.WithOwner()
                                        .HasForeignKey("StepConfigTestStepId");
                                });

                            b1.Navigation("Headers");

                            b1.Navigation("Selector");
                        });

                    b.Navigation("Config")
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.Execution", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.Project", b =>
                {
                    b.Navigation("Environments");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.TestCase", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
