// <auto-generated />
using System;
using AI.TestPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AI.TestPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20260820061639_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AIGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("AIPrompt")
                        .HasColumnType("text");

                    b.Property<string>("Browser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Timeout")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.TestStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AIElementDescription")
                        .HasColumnType("text");

                    b.Property<string>("AIInstruction")
                        .HasColumnType("text");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId", "StepOrder");

                    b.ToTable("TestSteps");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.Project", b =>
                {
                    b.HasOne("AI.TestPlatform.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.TestCase", b =>
                {
                    b.HasOne("AI.TestPlatform.Domain.Entities.TestCase", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AI.TestPlatform.Domain.Entities.Project", "Project")
                        .WithMany("TestCases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.TestStep", b =>
                {
                    b.HasOne("AI.TestPlatform.Domain.Entities.TestCase", "TestCase")
                        .WithMany("Steps")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AI.TestPlatform.Domain.Entities.StepConfig", "Config", b1 =>
                        {
                            b1.Property<Guid>("TestStepId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .HasColumnType("text");

                            b1.Property<string>("Endpoint")
                                .HasColumnType("text");

                            b1.Property<string>("Method")
                                .HasColumnType("text");

                            b1.Property<string>("Url")
                                .HasColumnType("text");

                            b1.HasKey("TestStepId");

                            b1.ToTable("TestSteps");

                            b1.ToJson("Config");

                            b1.WithOwner()
                                .HasForeignKey("TestStepId");

                            b1.OwnsMany("AI.TestPlatform.Domain.Entities.HeaderEntry", "Headers", b2 =>
                                {
                                    b2.Property<Guid>("StepConfigTestStepId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("StepConfigTestStepId", "Id");

                                    b2.ToTable("TestSteps");

                                    b2.WithOwner()
                                        .HasForeignKey("StepConfigTestStepId");
                                });

                            b1.OwnsOne("AI.TestPlatform.Domain.Entities.SelectorConfig", "Selector", b2 =>
                                {
                                    b2.Property<Guid>("StepConfigTestStepId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Description")
                                        .HasColumnType("text");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Value")
                                        .HasColumnType("text");

                                    b2.HasKey("StepConfigTestStepId");

                                    b2.ToTable("TestSteps");

                                    b2.WithOwner()
                                        .HasForeignKey("StepConfigTestStepId");
                                });

                            b1.Navigation("Headers");

                            b1.Navigation("Selector");
                        });

                    b.Navigation("Config")
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.Project", b =>
                {
                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("AI.TestPlatform.Domain.Entities.TestCase", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
